# supported characters
CHAR_VECTOR = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
# number of classes
NUM_CLASS = len(CHAR_VECTOR) + 1

NUM_EXAMPLES_PER_EPOCH_FOR_TRAIN = 513
NUM_EXAMPLES_PER_EPOCH_FOR_TEST = 58